require 'rake/packagetask'

Rake::PackageTask.new("works-api",:noversion) do |p|
    p.need_tar_gz = true
    p.package_files.include("**/*.*")
    p.package_files.exclude("log/**/*.*")
    p.package_files.exclude("tmp/**/*.*")
end



# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
